spring:
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
discodeit:
  storage:
    type: local
    local:
      root-path: ./storage

